name: nnels-local-d7
recipe: drupal7

# Config
config:
  webroot: web
  via: apache:2.4
  composer_version: "2.0.8"
  database: mariadb

# Services
services:
  appserver:
    type: php:7.2
    # xdebug: "debug,develop"
    build_as_root:
      - apt-get update
      - apt-get install mlocate
      - docker-php-ext-install sockets
      - pear install File_MARC-stable
      - pear install Validate_ISPN-alpha
    build:
      - composer install
      - mkdir -p ~/.drush/site-aliases
      - ln -sf /app/drush/nnels-local.aliases.drushrc.php ~/.drush/site-aliases/nnels-local.drushrc.php
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
    config:
      php: overrides/php.ini

  indexer:
      type: solr:6.6.6
      core: nnels-drupal
      config:
        conf: sites/all/modules/search_api_solr/solr-conf/6.x/
      overrides:
        environment:
          SOLR_DIR: /opt/solr/server/solr
      build:
        - echo "name=$LANDO_SOLR_CORE" > $SOLR_DIR/mycores/$LANDO_SOLR_CORE/core.properties
        - cp -r /app/web/sites/all/modules/search_api_solr/solr-conf/6.x/. $SOLR_DIR/mycores/$LANDO_SOLR_CORE/conf/

  mailcatch:
    type: mailhog
    portforward: 1025
    hogfrom:
      - appserver

  database:
    type: mariadb
    creds:
      user: nnels_rw
      password: nnels
      database: nnels_drupal7_local

  dbadmin:
    type: phpmyadmin
    hosts: database

  entitycache:
    type: memcached
    portforward: true

# Proxies
# NB: Add these entries to your /etc/hosts file.
proxy:
  appserver:
     - nnels.local
   dbadmin:
     - dbadmin.nnels.local
   # Not working
   # indexer:
   #   - indexer.nnels.local

# Tooling
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web
    env:
      DRUSH_OPTIONS_URI: nnels.local

# Events
events:
  post-db-import:
    - appserver: drush cc all
  post-rebuild:
    - appserver: drush --root=/app/web en devel -y
    - appserver: drush --root=/app/web dl field_sql_norevisions --dev
    - appserver: drush --root=/app/web en field_sql_norevisions -y
